### ISSUE TITLE
Site Launch Automation

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#2258]
#### User Story

A user should be able to go live through the Federalist interface and without making requests (ie: scan, cloudfront url) to federalist-support.

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [ ] Send email to GSA IT to scan site
- [ ] Respond with scan details status and report via email button/link
- [x] Generate/Update cloudfront url within Federalist
- [ ] Change made live via deploy of Federalist

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):
- [x] provision ses staging and store creds in staging service (federalist-staging-ses)
- [ ] create scan model and database table (site_id, site/demo, status (enum: pass/fail/pending, user), json_report)
- [ ] add cdn (json) and demoCDN (json) fields to site table
- [ ] Add a Scan button to Site Settings -> Live Site
- [ ] Add a Scan button to Site Settings -> Demo Site
- [ ] When scan button pressed, generate email (AWS SES) request to GSA IT to scan site at federalist-proxy path containing a response button/secure link (jsonwebtoken)
- [ ] Response page allows user to enter pass/fail status and upload report
- [ ] Response stored in scan table (site_id, site/demo, pass/fail/pending, json_report)
- [ ] Email scan requestor of scan status when scan record is updated/created
- [ ] if no cloudfront url exists and scan passed, button enabled to generate cloudfront url
- [ ] Add a button to Site Settings Live Site and Demo Site to to generate/update Cloudfront URL
- [ ] Display cdn-route details in Site Settings
- [ ] Enable "update" cloudfront url button if security certificate is not issued
- [ ] provision ses production and store creds in staging service (federalist-production-ses)

**Comment by davemcorwin** [comment]
Let's revisit post-SCR, some work has been regarding automing the CDN creation.
