### ISSUE TITLE
integrate contract information

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#2983]
#### User Story

<TODO>

#### Background (Optional)

Federalist repositories and are associated with contract data (name, dates, POC, ...)

#### Acceptance Criteria

- [ ] <TODO>
- [ ] Change made live via <TODO>.

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ] define data structure and import contract data
- [ ] identify/define flow of contract data to enter Federalist
- [ ] upon site creation associate w/ contract
- [ ] allow site users to identify technical contact(s)
....
