### ISSUE TITLE
Create integration and smoke tests for the platform.

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#3735]
To monitor the platform is operating as expected continuously and between deployments, implement integration and smoke tests.

## Background
Build out a framework to do this in Concourse - post SCR?

- [ ] High resolution liveness checks DURING deployments, particularly proxy, webhooks, etc
- [ ] post-deployment smoke tests for various apps
- [ ] Run Zap scans against staging and production site urls after updates to any of the supporting component/infra repos.
- [ ] New Relic pings for every custom domain 
- [ ] Deploy starter templates to verify they build and publish as expected with every platform deployment and change in the starter

**Comment by apburnes** [comment]
Added Zap scanning for sites after discussion with GSA IT Sec.
