### ISSUE TITLE
Epic: Outline and implement the architecture for multiple build tasks during a site build

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#3943]
To support more features and functions during the site build process, outline what the architecture could be to support multiple build checks during the site build. Additional build checks could be: static code scan, link checking, accessibility checks, site security scan, etc.

## Acceptance Criteria

- [x] #4168
  - PR https://github.com/cloud-gov/internal-docs/pull/122
  - How a queue could manage the checks
  - Define how a check could be run: before, during, or after site build complete
  - Where the checks could run: As an app task, a separate running app that handles task
- [x] #4169
  - A draft API for managing the checks
  - A proposed method for the checks to store results
- [x] #4170
- [x] #4172
- [x] #4171
--- 

## Security considerations
None

## Related Issues
Community supported resources for CI actions with Github or your CI of choice.

- https://github.com/cloud-gov/pages-core/issues/1112
- https://github.com/cloud-gov/pages-core/issues/907

```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/pages-core/issues/4168
- [ ] https://github.com/cloud-gov/pages-core/issues/4169
- [ ] https://github.com/cloud-gov/pages-core/issues/4172
- [ ] https://github.com/cloud-gov/pages-core/issues/4184
- [x] Talk dev tools team to understand their vision and how collaboration could work.
- [ ] https://github.com/cloud-gov/pages-core/issues/4170
- [ ] https://github.com/cloud-gov/pages-core/issues/4171
- [ ] https://github.com/cloud-gov/pages-core/issues/4185
- [ ] https://github.com/cloud-gov/pages-core/issues/4259
- [ ] https://github.com/cloud-gov/pages-core/issues/4260
- [ ] https://github.com/cloud-gov/pages-core/issues/4261
- [ ] https://github.com/cloud-gov/owasp-zap-task/issues/2

```

**Comment by drewbo** [comment]
Another option is to run these "within" pages either with the build or as a parallel process

**Comment by apburnes** [comment]
Rework this epic in planning on 10/02/2023 and create the next epic in the steps to a production build tasks.

**Comment by sknep** [comment]
See Epic #4327 for the next steps in release
