### ISSUE TITLE
Invitation URL is not copyable from alert popup

### ISSUE THREAD

**Issue by dawnpm** [cloud-gov/pages-core#4108]
When I invite a new user to https://pages.cloud.gov/organizations/33, I get a popup alert that says I should send the invitation URL to the person for them to create an account with cloud.gov. 

Expected results: I can triple click or click-and-drag the URL to select it, and then copy
Actual results: I cannot select the URL text in any way to get it into my clipboard.

## Notes

- browser is Version 112.0.5615.49 (Official Build) (x86_64)
- brief exchange in slack today: https://gsa-tts.slack.com/archives/C04823NMA/p1681304705651299
- previous longer exchange when I was trying to add two people, and had trouble with both: https://gsa-tts.slack.com/archives/C04823NMA/p1677088701848519

## Acceptance Criteria

- [ ] User can select the URL text to copy
- [ ] Alert text is updated to let the user know that the invitee should have received an invitation including the URL, and this is just a fallback in case they don't get that email.

Thanks!

```[tasklist]
### Tasks
- [x] Mock up changes to experience (Design, copy, etc
- [x] Review changes with dev team
- [ ] Implement changes to views
- [ ] Write tests & doublecheck linting
```

**Comment by apburnes** [comment]
@sknep this looks great. Do we also want an alert when updating an org member's role? Ie org `user` to `manager`

**Comment by sknep** [comment]
I think that alerts about edits to existing members (role change, removal, etc) would be hard to place in the page the way it exists now... I would want that notification in or very near to the edited member's row, as the user might have scrolled past the start of the table, or might not see past the last row, if the member list is long. Given we aren't paginating this table, there's not a great place to put that alert in... I do want to consider reworking this page generally, and would be able to accommodate better member edit confirmations in a future / larger scoped revision.

By the way, do you know if it's easy to access whether each invited member has 'accepted'? I'd like to allow org managers the option to resent an invitation, but only if the member hasn't yet accepted (created a pages account by logging in once). I'd need a way to identify those members separately if so...

**Comment by apburnes** [comment]
For resending invitations, there are some attributes that the UAA Identity provides to identify a users status but there are some nuances based on their IDP. We can do some testing to verify.

**Comment by svenaas** [comment]
@sknep You may already be considering this, but a situation that comes up sometimes (it came up this week) and will into the indefinite future is that the person who needs to be added is already the holder of an **unmigrated** Federalist account (i.e. without a UAA identity) that's in the way because it's already associated with their GitHub handle (or email address?).

I think mitigation options in this case are either

1. Remove the old account and create a new one (not sure how many orders the steps might occur in so I'm tagging @Ephraim-G and @drewbo who just worked through _one_ case) or

2. Migrate the old account (manually, in the database)

As an example, an 18F colleague might have used Federalist a great deal a few years ago, but wasn't actively using the tool when the Pages SCR happened, so they didn't migrate their account. Their understanding might be that they are already a user but maybe need to be activated or added to a site or an org or something. 

I don't know whether the response flow should account for this situation. @Ephraim-G may have the best sense of how frequently it occurs.

**Comment by drewbo** [comment]
Alerts look great. To continue @svenaas's point: I think if someone attempts to add a new user with a github handle that already exists in the database, they will get a 502 error. An improved (but relatively simple) process might be to catch that error and show a message that says something like "github handle already exists, please contact pages support"

**Comment by apburnes** [comment]
For non migrated user accounts. If you add the "new" user's Github handle in the invite, we check to see if that users exists already via the Github handle and then associate the UAA Identity to the user. The problem we run into is adding a "new" user without the Github handle and then once that new user associates their Github account to Pages we hit the error.

We need better error handling on the Github OAuth action.

**Comment by sknep** [comment]
![Screenshot 2023-12-06 at 1 20 02 PM](https://github.com/cloud-gov/pages-core/assets/4451344/377f83d9-8930-45af-a7f6-46d0ce945aeb)

**Comment by sknep** [comment]
Update: once we have removed the GitHub auth check in #4369 and are ready to create new invited emails (#4373) because we'll know who _actually_ needs a Cloud.gov IDP link (#https://github.com/cloud-gov/pages-core/issues/4370), we'll update the confirmation and error interactions to use these alert styles.
