### ISSUE TITLE
Wireframe how the UI for build tasks can be integrated into the current app build structure

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4170]
## User stories:

- As a developer or product owner responsible for ensuring that my agency's Pages site is secure and usable, I want to see if my code and site have any obvious security or usability problems.
- As a developer responsible for addressing security or accessibility issues for a Pages site, I want to know precisely where any discovered issues are, and see documentation or remediation steps for each issue.
- As a developer adding new features, or a content manager adding new content, I want to make sure that I am not introducing new security or usability/accessibility problems when I contribute to my Pages site, even on non-production branches.
- As a compliance analyst or site manager responsible for ensuring that my agency's technology products fulfill 21st Century IDEA, ATO, and SSP requirements, I want to directly access and keep records of my site's required scans.

## What is this for? Is it like GitHub's Actions, or GitLab's jobs?
Build tasks will be used primarily (or perhaps solely) to run automated tests on customer sites, either on the code itself at the beginning of the build, or on the generated site build after it is available on a preview link. They run concurrently, not in series, and do not imply a pipeline.

Notably, these tasks are not intended to be blocking -- which is to say, they will not fail or cancel a build, regardless of whether they complete or indicate concerns.

For now, the first/only scan we'll offer is a [ZAP](https://www.zaproxy.org/) vulnerability scan, which is intended to support BYO ATO customers provide monthly documentation that they meet required [vulnerability scanning requirements](https://csrc.nist.rip/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=RA-5). Later scans may support additional requirements identified for 21st Century IDEA compliance and other laws.

## What about site scanning? Can anyone else see the customer site scans?
The site scanning team has identified ZAP scans in their [candidate scans](https://github.com/GSA/site-scanning-documentation/blob/main/pages/candidate-scans.md) but have not yet implemented them or any other vulnerability/penetration testing scans. Additionally, as publishing these scans broadly would bring more attention to vulnerable Pages sites, these scan results will only be available to existing site/org users. That said, these vulnerabilities are public knowledge, which is why [CISA](https://www.cisa.gov/sites/default/files/publications/CISAInsights-Cyber-RemediateVulnerabilitiesforInternetAccessibleSystems_S508C.pdf) urges technology owners to remediate any issues found within 30 days.

## Potential Rollout
Team is deciding whether to enable scans by default for all customer sites and branches, or to make scans configurable, either by site or by branch. Considering cost of scans, value to customers, etc.  
Will likely identify this as a beta or experimental feature, so that we can more easily make adjustments without disrupting users. Intend to refine with user feedback after initial rollout. Testing "scans" rather than "tasks" as the nomenclature for usability -- and to make sure not to confuse with concepts like "jobs", "actions", "workflows", "pipelines" etc -- as those imply more control over the activities as well as concepts like sequencing and gating.

## Acceptance Criteria TBD

```[tasklist]
### Tasks
- [ ] Define schema for each task run, as well as each possible task type in the DB
- [ ] UI and workflow changes for site settings page (enable/disable tasks)
- [ ] UI and workflow for tasks for each build (view/download artifact(s), see task status)
- [ ] UI and workflow changes for build history log -- surface a link to tasks and artfacts
- [ ] Draft documentation for build tasks and individual scans available
- [ ] Draft customer communications about build tasks/scans (possibly note experimental feature, feedback welcome)
- [ ] Begin usability testing for build tasks/scans
- [ ] Identify metrics to monitor (& collection method/s) in order to determine feature usage/value to customers
```

**Comment by sknep** [comment]
Got a walkthru of the build tasks from Drew this morning,

**Comment by sknep** [comment]
Strawman for how this might look if we make the tasks customer-controlled and the artifacts viewable in the build logs:

![Build log page](https://github.com/cloud-gov/pages-core/assets/4451344/b06946fc-a265-4e20-b929-3088a60227f2)
![Site settings page](https://github.com/cloud-gov/pages-core/assets/4451344/7bb5f2e5-c2e4-4b0a-ad38-9197779f573c)

**Comment by apburnes** [comment]
The ran tasks table and site task settings look great!

For the ran tasks table, I think we can have it on it's own page so it doesn't need share with the build logs page. 

A site's build logs page is:
- `https://pages.cloud.gov/sites/<site-id>/builds/<build-id>/logs` 

So a site's build tasks could be at:
- `https://pages.cloud.gov/sites/<site-id>/builds/<build-id>/tasks`

Also, if you have any thoughts on how we can show the tasks on the build history page. 
<img width="834" alt="buildhistory" src="https://github.com/cloud-gov/pages-core/assets/693815/f1ea0720-5b89-4c8d-a15f-4d16671092e9">
Do we just have a link to the build's tasks or do we actually show task statuses?

**_Side note_**: We've used the accordion component as a catch all and it may not be the right use. If you have an opinion or alternatives, please share.

**Comment by sknep** [comment]
Ok I think these are the final set, but let me know if you have any other comments! @apburnes @drewbo @svenaas 

## Build history

Hopefully we can make something close to these changes.

![Build history](https://github.com/cloud-gov/pages-core/assets/4451344/7aa1e841-6e78-4f03-b35f-f5be4258d174)
----
## Scan results & Build logs

Note that the build info is up at the top of the page

![Scan results](https://github.com/cloud-gov/pages-core/assets/4451344/e1d6ffed-34b7-4ec8-a488-4bf25f8d209d)
----
Similar changes to the top of the build logs page, if possible/easy, to keep consistent with scan results

![Build log header](https://github.com/cloud-gov/pages-core/assets/4451344/93dd2839-297a-42f7-b923-0829492ec75e)
----
## Scan history (?)

Unsure if this is necessary. We'll see repeated sets of tests... I _think_ these are all the reasonable states that should be displayed to the user. The possible states for build tasks that I got earlier was `‘created’, ‘queued’, ‘tasked’, ‘error’, ‘processing’, ‘skipped’, ‘success’,` but not sure if it's up to date. Looks a lot like the build state list.

![Scan history](https://github.com/cloud-gov/pages-core/assets/4451344/133e779a-a452-4fdb-8223-5703bc42c472)

We'd need to put this in the left sidebar so people can find it, i'd probably put it above uploaded files but here's the icon / label:
![Scan results in sidebar](https://github.com/cloud-gov/pages-core/assets/4451344/2c8d34a3-7c62-46e2-868a-9f5180d595a8)

----

## Site Settings

(If/when we make these toggleable)

![Site settings page](https://github.com/cloud-gov/pages-core/assets/4451344/8ddebc89-9646-4800-bea9-18a9c28d60d0)
----

PS: I know we haven't picked an accessibility scan, but something that does WCAG 2.2 A and AA would be nice, when we get to it. ANDI is here just as placeholder.
