### ISSUE TITLE
Proposed Epic: Product Analytics

### ISSUE THREAD

**Issue by sknep** [cloud-gov/pages-core#4283]
This is about making sure we are gathering the awareness we need to make the product better for users.

**The opportunity:**
What are users doing in Pages? 
What are we making easier or harder for them?
What does it mean to make Pages “better”?

**Proposed approach & outcomes:**
Understand and document what users are doing, 
so that we can make better changes to support them, 
and measure the value of our product improvements.

**Proposed Task List:**
- [ ] Audit current events & DAP to document current impressions, visits, usage
- [ ] Identify gaps in current analytics information & what we need to estimate about our customers and their usage of the product
- [ ] Get clear on program and org goals that Pages product needs to demonstrate in order to secure future support
- [ ] Estimate what overall metrics will help with product prioritization and impact analysis, as well as communicating broadly about product/program health
- [ ] Identify what new direct metrics are needed (which events, what user / site / org characteristics to track, etc) that will help measure reach, usage and usability
- [ ] Add event tracking for key events, with appropriate user segmentation data (# of sites/orgs, org size, etc)
- [ ] Begin analysis and comparison of metrics over time, sharing reports and using them when evaluating significant changes and new features post-launch
- [ ] Expand feature flags to per-user or per-org for A/B testing to product to measure feature usage & impact on key customer metrics (currently FF are env-wide)
- [ ] (After 3 months?) Share metrics about users, sites, organizations, etc to organizational leaders and get feedback
- [ ] Schedule cadence of revisiting and revising both direct and computed metrics as we learn more
