### ISSUE TITLE
Proposed Epic: UX & Market Research

### ISSUE THREAD

**Issue by sknep** [cloud-gov/pages-core#4284]
This is about formulating product fit -- where we sit within the market, and how well we identify and serve our customers' needs. 

**The opportunity:**
Who are our current users? Our potential users?
What do our users really need from Pages?
What makes our users choose Pages among competitors?

**Proposed approach & outcomes:**
Understand and document our market fit,
so that we can prioritize work that makes customers choose us,
and drive adoption and cost recoverability / revenue

```tasklist
### Proposed Tasklist

- [ ] Collect any existing UX research about users, tasks, etc, even if it's old, and rev
- [ ] Look at current app event analytics around org/site/user and login to estimate a breakdown of user archetypes and their jobs to be done (JTBD)
- [ ] Interview users or user proxies from diverse orgs to validate/refine user archetypes & JTDBs
- [ ] Interview users/user proxies to understand ATO and SSP requirements and other 21C IDEA compliance activities
- [ ] Understand and document the New User Experience (NUX), then identify key opportunities for improvement
- [ ] Illustrate archetypes as personas and NUX as a Journey Map, then introduce to the team, begin using in product design and UX discussions
- [ ] Use personas, JTBDs, and NUX Journey Map to inform in-app analytics metrics and computed metrics
- [ ] Build a roster of volunteer users or user proxies representing various archetypes to participate in usability testing and feedback
- [ ] Pricing analysis?
- [ ] Document ways we continually react to research and user feedback, as required by 21C IDEA. Prepare quarterly/yearly reports communicating learnings and progress towards better CX for TTS leaders

```
