### ISSUE TITLE
Epic: Release Build Tasks

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4327]
```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/pages-cf-build-tasks/issues/4
- [ ] https://github.com/cloud-gov/pages-core/issues/4382
- [ ] https://github.com/cloud-gov/pages-core/issues/4395
- [ ] https://github.com/cloud-gov/pages-cf-build-tasks/issues/10
- [ ] https://github.com/cloud-gov/pages-core/issues/4403
- [ ] https://github.com/cloud-gov/pages-core/issues/4404
- [ ] https://github.com/cloud-gov/pages-core/issues/4407
- [ ] https://github.com/cloud-gov/pages-core/issues/4408
- [ ] https://github.com/cloud-gov/pages-core/issues/4410
- [ ] https://github.com/cloud-gov/pages-core/issues/4485
- [ ] https://github.com/cloud-gov/pages-core/issues/4411
- [ ] https://github.com/cloud-gov/pages-core/issues/4532
- [ ] https://github.com/cloud-gov/pages-core/issues/4530
- [ ] https://github.com/cloud-gov/pages-core/issues/4409
- [ ] https://github.com/cloud-gov/pages-core/issues/4406
- [ ] https://github.com/cloud-gov/pages-core/issues/4261
- [ ] https://github.com/cloud-gov/pages-core/issues/4539
- [ ] https://github.com/cloud-gov/pages-core/issues/4573
- [ ] https://github.com/cloud-gov/pages-cf-build-tasks/issues/36
- [ ] https://github.com/cloud-gov/pages-core/issues/4581
- [ ] https://github.com/cloud-gov/pages-core/issues/4529
- [ ] https://github.com/cloud-gov/pages-core/issues/4405
- [ ] https://github.com/cloud-gov/pages-core/issues/4448
- [ ] https://github.com/cloud-gov/pages-core/issues/4598
- [ ] https://github.com/cloud-gov/pages-core/issues/4447
- [ ] https://github.com/cloud-gov/pages-core/issues/4614
```

**Comment by drewbo** [comment]
Released!
