### ISSUE TITLE
Epic: ATOaaS

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4329]
Creating a streamlined process to get an ATO for Pages customers needing their own ATO. ATO as a Service (ATOaaS)
```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/pages-core/issues/4364
- [ ] https://github.com/cloud-gov/pages-core/issues/4365
- [x] Provide generalized template for Customer to fill out ATO
- [x] ~provide any additional written guidance on how to meet the controls for a Pages site~ (https://github.com/cloud-gov/pages-core/issues/4430)
- [ ] ~Document/implement onboarding process and add to the website~ (#4430)
- [x] Related Epic: See more for next PI at https://github.com/cloud-gov/pages-core/issues/4430
- [x] see more for next PI at https://github.com/cloud-gov/pages-core/issues/4430
```

**Comment by apburnes** [comment]
Completed.
