### ISSUE TITLE
Epic: NUX for Invited Users

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4359]
As an org manager inviting a new user to their Pages org, I want the invited user to have a smooth onboarding process onto the Pages platform with easy access to our Pages org.

```[tasklist]
### Tasks
- [x] Document/ illustrate current invite flow (https://drive.google.com/file/d/1K2rw05hPmTRN5Rs082NQ9Sam6U4TKzfI/view?usp=drive_link)
- [ ] https://github.com/cloud-gov/pages-core/issues/4305
- [ ] https://github.com/cloud-gov/pages-core/issues/4369
- [ ] https://github.com/cloud-gov/pages-core/issues/4372
- [ ] https://github.com/cloud-gov/uaa-customized-boshrelease/issues/43
- [ ] https://github.com/cloud-gov/pages-core/issues/4363
- [ ] #4108
- [ ] https://github.com/cloud-gov/pages-core/issues/4370
- [ ] https://github.com/cloud-gov/pages-core/issues/4373
- [ ] https://github.com/cloud-gov/pages-core/issues/4371
- [ ] https://github.com/cloud-gov/pages-core/issues/4381
- [ ] ----- the following are deprioritized for this epic ------
- [ ] Allow an org manager to reactivate an existing user who hasn't logged in for 90 days and is now deactivated per Cloud.gov IDP account policy (like a button! similar to Resend Invite in #4371)
- [ ] Find a way to identify users by age of acct(?) to get NUX metrics
- [ ] Clarify User vs Member in Org Management page?
- [ ] Add "Drip" campaign / follow up emails to unclaimed accts
- [ ] DIY Pages Sandbox provisioning?
- [ ] Notify existing Pages users when someone adds them to a new org
```

**Comment by sknep** [comment]
Calling this epic complete!
