### ISSUE TITLE
Epic: App User Event Tracking

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4360]
As a team, we want to better understand how our users are interacting with the platform through more robust event tracking.

```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/pages-core/issues/4451
- [ ] https://github.com/cloud-gov/pages-core/issues/4449
- [ ] https://github.com/cloud-gov/pages-core/issues/4453
- [ ] https://github.com/cloud-gov/pages-core/issues/4454
- [ ] https://github.com/cloud-gov/pages-core/issues/4455
- [ ] Watch, assess, make it better
```
