### ISSUE TITLE
Epic: Container Hardening and Scanning

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4361]
Improve the security posture of our CI and Platform environments by running tasks and apps in hardened containers. Considered this epic complete when we've hardened every task that is currently available.

```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/pages-core/issues/4362
- [ ] #4263
- [ ] https://github.com/cloud-gov/private/issues/646
- [ ] https://github.com/cloud-gov/private/issues/649
- [ ] https://github.com/cloud-gov/pages-core/issues/4378
- [ ] https://github.com/cloud-gov/pages-core/issues/4384
- [ ] https://github.com/cloud-gov/pages-core/issues/4385
- [ ] https://github.com/cloud-gov/pages-core/issues/4386
- [ ] https://github.com/cloud-gov/pages-proxy/issues/201
- [ ] https://github.com/cloud-gov/pages-cf-build-tasks/issues/6
- [ ] https://github.com/cloud-gov/pages-gpg-keys/issues/2
- [ ] https://github.com/cloud-gov/pages-mailer/issues/34
- [ ] https://github.com/cloud-gov/pages-redirects/issues/236
- [ ] https://github.com/cloud-gov/pages-core/issues/4394
- [ ] https://github.com/cloud-gov/pages-core/issues/4432
- [ ] https://github.com/cloud-gov/pages-core/issues/4433
```
