### ISSUE TITLE
Update NUX "you're invited" emails (new design, new content)

### ISSUE THREAD

**Issue by sknep** [cloud-gov/pages-core#4373]
After #4370, we will probably need two emails -- one to send to users we expect to use Cloud.gov's IDP to create their Pages/Cloud.gov account, and one for users we expect to use an agency IDP based on their email domain.

```[tasklist]
### Tasks
- [x] Design and code a new basic HTML email template for Cloud.gov
- [x] Draft content for the two welcome emails, get any approvals
- [x] Implement the two emails
- [ ] Find a way to do some inbox testing (see if anyone has a license for Litmus or something like that)
- [ ] Investigate why email invites occasionally do not make it potential new users inboxes/spam
```
