### ISSUE TITLE
Create SCR for Build Tasks

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4382]
Create and complete the SCR for Build tasks

## Acceptance Criteria
- [x] Add SCR request to FedRAMP SCR form
- [x] Fill out impacted controls and system components
- [x] Provide documentation on how the new service will work within existing 
- [x] Use the documentation provided to adapt SSP in the future
```[tasklist]
### Tasks
```

**Comment by kudehaatila** [comment]
Preparing a consolidated SIA document to use toward finalizing the SCR:
•	SSPP front matter updates
•	Control analysis for impacted control selection
•	Supporting documents updates
•	Artifacts collection
•	SSPP review and updates

**Comment by apburnes** [comment]
SCR Submitted.
