### ISSUE TITLE
Epic: Decide on build tasks release plan

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#4406]
Our rough release plan for build tasks will be to complete the below features/issues and then start a targeted roll-out of build tasks for testing purposes. We'll then reassess the tasks to be completed before doing a larger rollout

```[tasklist]
### Pre-Beta Release Tasks
- [ ] https://github.com/cloud-gov/pages-core/issues/4404
- [ ] https://github.com/cloud-gov/pages-core/issues/4410
- [ ] https://github.com/cloud-gov/pages-core/issues/4439
- [ ] https://github.com/cloud-gov/pages-cf-build-tasks/issues/19
- [ ] https://github.com/cloud-gov/pages-core/issues/4473
- [ ] https://github.com/cloud-gov/pages-core/issues/4407
- [ ] https://github.com/cloud-gov/pages-core/issues/4408
- [ ] https://github.com/cloud-gov/pages-core/issues/4476
- [ ] https://github.com/cloud-gov/pages-cf-build-tasks/issues/25
- [ ] https://github.com/cloud-gov/pages-core/issues/4446
- [ ] https://github.com/cloud-gov/pages-core/issues/4411
- [ ] https://github.com/cloud-gov/pages-core/issues/4409
```

**Comment by sknep** [comment]
We can close out this epic now that everything's complete, in favor of https://github.com/cloud-gov/pages-core/issues/4327
