### ISSUE TITLE
Update/verify every pipeline is using the hardened node, python, oci build task and docker in docker in CI tasks

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4432]
Also checking for redis, postgres, nginx, and github-release as those are now available.

```[tasklist]
### Tasks
- [x] pages-core: https://github.com/cloud-gov/pages-core/pull/4503
- [x] pages-build-container: https://github.com/cloud-gov/pages-build-container/pull/463
- [x] pages-proxy: https://github.com/cloud-gov/pages-proxy/pull/206
- [x] pages-gpg-keys: verified hardening complete
- [x] pages-redirects: verified hardening complete
- [x] pages-mailer: verified hardening complete
- [x] pages-cf-build-tasks: https://github.com/cloud-gov/pages-cf-build-tasks/pull/32
- [x] ensure all repos are using hardened images with docker in docker
```
