### ISSUE TITLE
Create an updated ATU process flow slide for easy reference and understanding.

### ISSUE THREAD

**Issue by KKAtila** [cloud-gov/pages-core#4458]
```[tasklist]
### Tasks
- [x] Gather available feedback for ATU process
- [x] Update the ATU Process flow
- [x] Finalize the ATU Process flow slide and get it ready for distribution/upload on cg Pages website
```

**Comment by KKAtila** [comment]
No feedback from customers yet.

**Comment by apburnes** [comment]
@KKAtila can we close this issue?
