### ISSUE TITLE
Organize the documents into categories for ease of navigation.

### ISSUE THREAD

**Issue by KKAtila** [cloud-gov/pages-core#4461]
```[tasklist]
### Tasks
- [x] Organize the Documents
- [x] Develop a structured folder system to store the documents
- [ ] ~Set up a regular review process to keep documents updated (Maintenance)~
```

**Comment by apburnes** [comment]
Complete
