### ISSUE TITLE
Epic: Research and plan fully managed website product

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4489]
An initial issue to track a possible future CMS offering.

```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/pages-core/issues/4574
- [ ] https://github.com/cloud-gov/pages-core/issues/4576
- [ ] https://github.com/cloud-gov/pages-core/issues/4629
- [ ] https://github.com/cloud-gov/pages-core/issues/4730
- [ ] https://github.com/cloud-gov/pages-core/issues/4731
- [ ] https://github.com/cloud-gov/pages-core/issues/4615
- [ ] https://github.com/cloud-gov/pages-core/issues/4732
- [ ] https://github.com/cloud-gov/pages-editor/issues/1
- [ ] Outline management path to maintain layouts, components and theming.
```

**Comment by drewbo** [comment]
Some initial thoughts here: https://docs.google.com/document/d/1BdMIdohE35znjpy2hG5NPxGfvzIg319t1g2oMYECBl8/edit
