### ISSUE TITLE
Create Config Mgmt plan for Pages

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4528]
Create a document outlining the configuration management plan for Pages.

## Acceptance Criteria
- [ ] TBD
```[tasklist]
### Tasks
- [x] Created a new CMP
- [x] Shared with the team for review and comments
- [x] Finalized the document
```
