### ISSUE TITLE
Refactor concourse pipelines

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#4540]
We'd like to refactor our concourse pipelines for greater consistency across our repos. We've set up [pages-pipeline-tasks](https://github.com/cloud-gov/pages-pipeline-tasks/) to assist with this. Roughly:
- Abstract common tasks into tasks/scripts
- Add common/repeated resources/resource types to the overlays here to be replaced by [`ytt`](https://carvel.dev/ytt/)
- Move all our repositories to having one long-running branch (`main`) and setup the pipelines so that PRs deploy to dev, merges to main deploy to staging, and new matching tags deploy to production
- Semi-automate the release process like in this repo: we have an auto-updating release branch which when merged creates a new tag/release/deploy to production
- Any other simplifications we see that can do across our pipelines now that container hardening is complete.

Resources:
- https://docs.google.com/spreadsheets/d/1WJqK-wKLrnxYZhd1RHq1w-t6RQu3a58JlU_UuW9NjcQ/edit#gid=0
```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/pages-build-container/issues/472
- [ ] https://github.com/cloud-gov/pages-proxy/pull/212
- [ ] https://github.com/cloud-gov/pages-mailer/pull/43
- [ ] https://github.com/cloud-gov/pages-core/issues/4548
- [ ] https://github.com/cloud-gov/pages-redirects/issues/249
- [ ] https://github.com/cloud-gov/pages-cf-build-tasks/issues/37
```

**Comment by drewbo** [comment]
Still likely to tinker with a few pipelines after the fact but this is done!
