### ISSUE TITLE
Epic: Review and update templates based on the customers the feedback and Supported-ATU experience.

### ISSUE THREAD

**Issue by KKAtila** [cloud-gov/pages-core#4633]
## Acceptance Criteria
Continuous review and update for the ATU templates.

- [x] #4680
- [x] #4634
- [x] #4681
- [x] #4685
- [x] #4686
- [x] #4737
- [x] Contingency Plan (CP) - Moved to Epic: ATU Next #4618
- [x] Incident Response Plan (IRP) - Moved to Epic: ATU Next #4618
- [x] #4738 - Moved to Epic: ATU Next #4618
- [x] #4735
