### ISSUE TITLE
NCD ATU Tracking

### ISSUE THREAD

**Issue by KKAtila** [cloud-gov/pages-core#4659]
ATU Documentation Tracking for ATU-Supported Customers

We have begun receiving requests for ATU Support and our objective is to track the work provided for each customer through the ATU structured process until the ATU Letter is signed.

Documentation: Gathering and organizing relevant information.
Assessment: Reviewing and evaluating the collected information.
ATU Approval Decision Making: Making decision based on the assessment and sign the ATU Letter.
Acceptance Criteria

Current customer is NCD
- [ ] Documentation: Gathering and organizing relevant information.
- [ ]  Assessment: Reviewing and evaluating the collected information.
- [ ]  ATU Approval Decision Making: Making decision based on the assessment and sign the ATU Letter.

**Comment by KKAtila** [comment]
Reviewed the documents and met with Jason (11/20) to provide feedback and guidance.

**Comment by hursey013** [comment]
@KKAtila Let me know if we can close this out!

**Comment by KKAtila** [comment]
@hursey013 Please go for it. Thanks
